### ISSUE TITLE
403 error from Odoo since last update

### ISSUE THREAD

**Issue by danduk82** [camptocamp/gtimelog2odoo#25]
Since the last Odoo update I always get the following error with the attendance submission. Does anyone else has this problem?
The Jira things are working well, only problem with the Odoo stuff.

I have updated the credentials in my rc file and secrets with the new odoo credentials. Is there something more to do?

```
Traceback (most recent call last):
  File "/home/aborghi/code/gtimelog2odoo/./exporter.py", line 306, in <module>
    odoo.drop_attendances(config['date_window'])
  File "/home/aborghi/code/gtimelog2odoo/wrappers/odoo_client.py", line 32, in drop_attendances
    employee_id = self._attendance_defaults()["employee_id"]
  File "/home/aborghi/code/gtimelog2odoo/wrappers/odoo_client.py", line 28, in _attendance_defaults
    self._attendance_default = self.client.env["hr.attendance"].default_get(["employee_id"])
  File "/home/aborghi/.venv/lib/python3.10/site-packages/odoorpc/env.py", line 278, in __getitem__
    self.registry[model] = self._create_model_class(model)
  File "/home/aborghi/.venv/lib/python3.10/site-packages/odoorpc/env.py", line 322, in _create_model_class
    fields_get = self._odoo.execute(model, 'fields_get')
  File "/home/aborghi/.venv/lib/python3.10/site-packages/odoorpc/odoo.py", line 429, in execute
    data = self.json(
  File "/home/aborghi/.venv/lib/python3.10/site-packages/odoorpc/odoo.py", line 271, in json
    data = self._connector.proxy_json(url, params)
  File "/home/aborghi/.venv/lib/python3.10/site-packages/odoorpc/rpc/jsonrpclib.py", line 113, in __call__
    response = self._opener.open(request, timeout=self._timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by leemannd** [comment]
Hello I have the same issue. I have asked into the camptocamp odoo slack channel
